const TOP_PAGE_LIST = "TOP_PAGE_LIST";
const TOP_RES_INIT = "TOP_RES_INIT";
const TOP_RES_SET = "TOP_RES_SET";

const RES_PAGE_OBJ = "RES_PAGE_OBJ";
const RES_IMG_BATE = "RES_IMG_BATE";
export default {
	TOP_PAGE_LIST,
	TOP_RES_SET,
	TOP_RES_INIT,
	RES_PAGE_OBJ,
	RES_IMG_BATE
}