const ALL_PAGE_DATA = "ALL_PAGE_DATA";

const TOP_PAGE_LIST = "TOP_PAGE_LIST";
const TOP_RES_INIT = "TOP_RES_INIT";
const TOP_RES_SET = "TOP_RES_SET";

export default {
	ALL_PAGE_DATA,
	TOP_PAGE_LIST,
	TOP_RES_SET,
	TOP_RES_INIT
}