const WEIXIN_LOGIN="WEIXIN_LOGIN";
const WEIXIN_SET_TOKEN = "WEIXIN_SET_TOKEN";

const TOP_PAGE_LIST = "TOP_PAGE_LIST";
const TOP_RES_INIT = "TOP_RES_INIT";
const TOP_RES_SET = "TOP_RES_SET";

const RES_PAGE_OBJ = "RES_PAGE_OBJ";
const RES_IMG_BATE = "RES_IMG_BATE";
const RES_SET_UOID = "RES_SET_UOID";
export default {
	WEIXIN_LOGIN,
	WEIXIN_SET_TOKEN,
	TOP_PAGE_LIST,
	TOP_RES_SET,
	TOP_RES_INIT,
	RES_PAGE_OBJ,
	RES_IMG_BATE,
	RES_SET_UOID
}